### ISSUE TITLE
LICENSE question

### ISSUE THREAD

**Issue by ekigwana** [morgan-at-keysight/socketscpi#3]
Is this code also available under a license similar to [pyarbtools LICENSE](https://github.com/morgan-at-keysight/pyarbtools/blob/master/LICENSE) ?

I am using Keysight instruments and would like to use pyarbtools but it pulls in this module which is GPL. That means
that pyarbtools has to be licensed using GPL because it is using this module. And since my code is would be using pyarbtools, my code would have to be GPL as well. Hence the question.

**Comment by morgan-at-keysight** [comment]
Changed to MIT license.
