### ISSUE TITLE
socketscpi takes much more time than pure visa reading function

### ISSUE THREAD

**Issue by xn007** [morgan-at-keysight/socketscpi#4]
* socketscpi version: socketscpi 2020.5.0 
* Python version: 3.8.6
* Operating System: Windows 10

### Description
Time duration difference for same binary array reading:
socketscpi: more than 100ms
visa read in **sync** mode (LabView visa function used): about 5ms

Could you have a look? Thanks very much!

**Comment by morgan-at-keysight** [comment]
I have not seen timing discrepancies like this in my testing. 

Can you provide more details on this issue?

- What test equipment are you using?
- How big is the array of data?
- Does the LabVIEW code do anything differently than the Python code where you see the large delay?

**Comment by xn007** [comment]
Hi Morgan, 
Thanks very much for your time!
Finally, I found my team member added a 100ms delay between write and read operaton in "binblockread" function. 
        # Send command/query
        self.write(cmd)
        **_sleep(0.1)_**
        # Read # character, raise exception if not present.
        if self.socket.recv(1) != b'#':
            raise BinblockError('Data in buffer is not in binblock format.')

Because, without the delay, it will generate an error message when Python run it in a child process.
**File "C:\Users\dev\AppData\Local\Programs\Python\Python38\lib\site-packages\socketscpi\socketscpi.py", line 183, in binblockread
    if self.socket.recv(1) != b'#':
BlockingIOError: [WinError 10035] A non-blocking socket operation could not be completed immediately**

The Python code is as below:
`import socketscpi
import time
import os
from multiprocessing import Process

class socketProcess(Process):
    def __init__(self, socketScpi: socketscpi.SocketInstrument, daemon=False):
        super().__init__(daemon=daemon)
        self.session = socketScpi
        self.idn = self.session.instId.strip()
        print(f'initial scpi socket for instrument: {self.idn}')

    def run(self):
        index = 10
        print(f'run socket scpi in process: {os.getpid()}')
        while index > 0:
            start = time.time()
            traceData = self.session.binblockread(':FORM REAL,32;:TRAC? TRACE1', datatype='f').newbyteorder()
            end = time.time()
            print(f'socket scpi first 5 chars: {traceData[:5]} of total points: {traceData.size}')
            print(f'socket scpi read trace data time cost: {end - start} seconds')
            index -= 1
        self.session.disconnect()

if __name__ == '__main__':
    ip = '169.254.41.184'
    socketScpi = socketscpi.SocketInstrument(ip)
    processSocketSCPI = socketProcess(socketScpi)
    processSocketSCPI.start()
`

Of cause, socketscpi works well if Python run it in main thread.
It takes less than 10ms to read 6001 float points from Keysight PNA 9030B spectrum analyzer when all socketscpi function running in main thread (without multiprocessing). Super fast indeed!

But our test environment need multiprocessing, so I need create child process to each analyzer to simulate it as almost real time measurement. The extra delay should be deleted and with no error.
Please help! Thanks very much!

**Comment by xn007** [comment]
Sorry, it is my own fault for child process handling. Thanks for your time!
