### ISSUE TITLE
Timeouts with binblockwrite

### ISSUE THREAD

**Issue by stesteve** [morgan-at-keysight/socketscpi#5]
* socketscpi version: 2020.5.0
* Python version: 3.8.5
* Operating System: Linux

### Description

The socket.sendall() function should be used instead of socket.send() when sending data in the binblockwrite function.  I observed timeouts with the ESR? query that comes after when sending long blocks of data with send().  The recommended change to line 260 is shown below: 

```
       # Send message, header, data, and termination
        self.socket.send(cmd.encode('latin_1'))
        self.socket.send(header.encode('latin_1'))
        self.socket.sendall(data)
        self.socket.send(b'\n')
```

**Comment by morgan-at-keysight** [comment]
Thanks for looking into this. I have seen one other PyArbTools issue raised that recommends the change from `.send()` to `.sendall()`. I will run some tests to make sure it doesn't break anything and push the recommended changes.

**Comment by morgan-at-keysight** [comment]
I have updated `binblockread` to use `socket.sendall()`. Please update to socketscpi version 2021.07.0.
